source 'http://rubygems.org'

gem 'activesupport', '~> 5.0'
gem 'padrino-helpers', '~> 0.12'
gem 'rack-cache', '~> 1.0'
gem 'rake'
gem 'sinatra', '~> 1.4'
gem 'sinatra-flash', '~> 0.3'
gem 'sinatra-static-assets', '~> 1.0'
gem 'haml'

group :development do
  gem 'better_errors'
  gem 'guard-rubocop'
  gem 'haml-lint'
  gem 'scss-lint'
  gem 'shotgun'
  gem 'thin', '~> 1.6'
end

group :test do
  gem 'rspec'
end
